FIGHT_DIFFICULTY_UNKNOWN = None
FIGHT_DIFFICULTY_RAID = 100
FIGHT_DIFFICULTY_SAVAGE = 101

PARTY_SIZE_LIGHT_PARTY = 4
PARTY_SIZE_FULL_PARTY = 8

EVENT_TYPE_COMBATANT_INFO = 'combatantinfo'
EVENT_TYPE_BEGINCAST = 'begincast'
EVENT_TYPE_CAST = 'cast'
EVENT_TYPE_DAMAGE = 'damage'
EVENT_TYPE_HEAL = 'heal'
EVENT_TYPE_CALCULATED_DAMAGE = 'calculateddamage'
EVENT_TYPE_APPLY_BUFF = 'applybuff'
EVENT_TYPE_REFRESH_BUFF = 'refreshbuff'
EVENT_TYPE_REMOVE_BUFF = 'removebuff'
EVENT_TYPE_LB_UPDATE = 'limitbreakupdate'
EVENT_TYPE_APPLY_DEBUFF = 'applydebuff'
EVENT_ENCOUNTER_END = 'encounterend'
